arena_ir_state_adapter:
  ros__parameters:
    publish_period_sec: 0.1
    source_timeout_sec: 0.5
    ir_low_sample_count: 3
    ir_trip_distance_front: 0.08
    ir_trip_distance_front_left: 0.08
    ir_trip_distance_front_right: 0.08
    ir_trip_distance_left: 0.08
    ir_trip_distance_right: 0.08
    ir_trip_distance_back: 0.08
    source_sensor_for_front: front
    source_sensor_for_front_left: front_left
    source_sensor_for_front_right: front_right
    source_sensor_for_left: left
    source_sensor_for_right: right
    source_sensor_for_back: back

arena_roamer:
  ros__parameters:
    ir_display_distance_front: 0.08
    ir_display_distance_front_left: 0.08
    ir_display_distance_front_right: 0.08
    ir_display_distance_left: 0.08
    ir_display_distance_right: 0.08
    ir_display_distance_back: 0.08
