missions:
  default_original:
    mission_name: default_original
    source: template
    mission_mode: default_original
    waypoints:
      - position: [0.70, -2.40, 0.0]
        arrival_yaw: 1.5707963267948966
        position_tolerance: 0.05
        dwell_time: 0.0
      - position: [-0.70, 0.00, 0.0]
        arrival_yaw: 1.5707963267948966
        position_tolerance: 0.05
        dwell_time: 0.0
      - position: [0.70, 2.40, 0.0]
        arrival_yaw: 1.5707963267948966
        position_tolerance: 0.05
        dwell_time: 0.0

saved_routines: {}
