[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
board_microros_transport = serial
board_microros_distro = jazzy
monitor_speed = 115200
lib_ldf_mode = deep+
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio
build_flags =
    -std=gnu++17
